import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

import { Field } from '../../../models/field.model';
import { FormSchema } from '../../../models/form-schema.model';
import { Submission, SubmissionValue } from '../../../models/submission.model';

import { resolveRepeaterItemLabel } from './form-model.factory';
import { formatSubmissionDisplayValue } from './submission-value.formatter';

const PDF_COLORS = {
  sage: [107, 143, 113] as [number, number, number],
  sageDark: [79, 109, 90] as [number, number, number],
  terracotta: [201, 124, 93] as [number, number, number],
  charcoal: [45, 45, 45] as [number, number, number],
  muted: [100, 100, 100] as [number, number, number],
  divider: [210, 218, 212] as [number, number, number],
};

const PAGE_MARGIN = 18;
const FOOTER_HEIGHT = 14;

interface PdfFieldGroup {
  title: string;
  fields: Field[];
}

/** Returns schema fields present in the submission, preserving schema order. */
export function getSubmittedFieldsInOrder(schema: FormSchema, submission: Submission): Field[] {
  return schema.fields.filter((field) => field.key in submission);
}

/** Groups submitted body fields separated by gaps in schema field order. */
function groupSubmittedBodyFields(schema: FormSchema, submission: Submission): PdfFieldGroup[] {
  const bodyFields = getSubmittedFieldsInOrder(schema, submission).filter(
    (field) => field.readonly !== true && field.type !== 'repeater',
  );

  const groups: Field[][] = [];
  let currentGroup: Field[] = [];

  for (const field of bodyFields) {
    if (currentGroup.length === 0) {
      currentGroup.push(field);
      continue;
    }

    const previousIndex = schema.fields.indexOf(currentGroup[currentGroup.length - 1]);
    const currentIndex = schema.fields.indexOf(field);

    if (currentIndex - previousIndex > 1) {
      groups.push(currentGroup);
      currentGroup = [field];
    } else {
      currentGroup.push(field);
    }
  }

  if (currentGroup.length > 0) {
    groups.push(currentGroup);
  }

  return groups.map((fields) => ({
    title: inferSectionTitle(schema, submission, fields),
    fields,
  }));
}

/** Derives a generic section title from schema context — no field-name hardcoding. */
function inferSectionTitle(schema: FormSchema, submission: Submission, group: Field[]): string {
  const firstIndex = schema.fields.indexOf(group[0]);

  if (firstIndex <= 0) {
    return 'Application Details';
  }

  const submittedBefore = schema.fields
    .slice(0, firstIndex)
    .filter((field) => field.key in submission);

  for (let index = submittedBefore.length - 1; index >= 0; index--) {
    const candidate = submittedBefore[index];

    if (candidate.type === 'dropdown') {
      const label = formatSubmissionDisplayValue(candidate, submission[candidate.key]);

      if (label) {
        return label;
      }
    }
  }

  return group[0].label;
}

function formatSubmissionTimestamp(date: Date): string {
  return new Intl.DateTimeFormat('en-GB', {
    day: '2-digit',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  }).format(date);
}

function sanitizeFilename(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function drawPageFooter(doc: jsPDF, pageNumber: number, totalPages: number): void {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const footerY = pageHeight - 10;

  doc.setDrawColor(...PDF_COLORS.divider);
  doc.line(PAGE_MARGIN, footerY - 4, pageWidth - PAGE_MARGIN, footerY - 4);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...PDF_COLORS.muted);
  doc.text('Generated by FormFlow', PAGE_MARGIN, footerY);
  doc.text(`Page ${pageNumber} of ${totalPages}`, pageWidth - PAGE_MARGIN, footerY, {
    align: 'right',
  });
}

function ensurePageSpace(doc: jsPDF, y: number, requiredHeight: number): number {
  const pageHeight = doc.internal.pageSize.getHeight();

  if (y + requiredHeight <= pageHeight - FOOTER_HEIGHT) {
    return y;
  }

  doc.addPage();
  return PAGE_MARGIN;
}

function drawSectionHeading(doc: jsPDF, title: string, y: number): number {
  const pageWidth = doc.internal.pageSize.getWidth();
  y = ensurePageSpace(doc, y, 18);

  doc.setDrawColor(...PDF_COLORS.divider);
  doc.setLineWidth(0.4);
  doc.line(PAGE_MARGIN, y, pageWidth - PAGE_MARGIN, y);
  y += 6;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(...PDF_COLORS.sage);
  doc.text(title.toUpperCase(), PAGE_MARGIN, y);
  return y + 4;
}

function drawLabelValueTable(doc: jsPDF, rows: [string, string][], y: number): number {
  if (rows.length === 0) {
    return y;
  }

  autoTable(doc, {
    startY: y,
    body: rows,
    theme: 'plain',
    styles: {
      fontSize: 10,
      cellPadding: { top: 3, right: 2, bottom: 3, left: 0 },
      textColor: PDF_COLORS.charcoal,
      lineColor: PDF_COLORS.divider,
      lineWidth: 0.1,
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 58, textColor: PDF_COLORS.sageDark },
      1: { cellWidth: 'auto' },
    },
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
  });

  return (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
}

/** Builds PDF rows for a nested repeater submission value. */
export function buildRepeaterPdfSections(
  field: Field,
  value: SubmissionValue,
): { title: string; rows: [string, string][] }[] {
  if (!Array.isArray(value)) {
    return [];
  }

  const childFields = field.fields ?? [];
  const sections: { title: string; rows: [string, string][] }[] = [];

  value.forEach((row, index) => {
    if (!row || typeof row !== 'object' || Array.isArray(row)) {
      return;
    }

    const rowRecord = row as Record<string, SubmissionValue>;
    const rows: [string, string][] = [];

    for (const child of childFields) {
      if (!(child.key in rowRecord)) {
        continue;
      }

      rows.push([child.label, formatSubmissionDisplayValue(child, rowRecord[child.key])]);
    }

    sections.push({
      title: `${field.label} — ${resolveRepeaterItemLabel(field, index)}`,
      rows,
    });
  });

  return sections;
}

/** Generates and downloads a schema-driven PDF for the given submission. */
export function downloadSubmissionPdf(schema: FormSchema, submission: Submission): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = PAGE_MARGIN;

  doc.setFillColor(...PDF_COLORS.sage);
  doc.rect(0, 0, pageWidth, 28, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(255, 255, 255);
  doc.text('FormFlow', PAGE_MARGIN, 14);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('Dynamic Form Renderer', PAGE_MARGIN, 21);

  y = 38;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...PDF_COLORS.charcoal);
  doc.text(schema.title, PAGE_MARGIN, y);
  y += 10;

  const metaRows: [string, string][] = [['Submission Date', formatSubmissionTimestamp(new Date())]];

  for (const field of getSubmittedFieldsInOrder(schema, submission)) {
    if (field.readonly === true) {
      metaRows.push([field.label, formatSubmissionDisplayValue(field, submission[field.key])]);
    }
  }

  autoTable(doc, {
    startY: y,
    body: metaRows,
    theme: 'plain',
    styles: {
      fontSize: 10,
      cellPadding: { top: 2.5, right: 2, bottom: 2.5, left: 0 },
      textColor: PDF_COLORS.charcoal,
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 52, textColor: PDF_COLORS.sageDark },
      1: { cellWidth: 'auto' },
    },
    margin: { left: PAGE_MARGIN, right: PAGE_MARGIN },
  });

  y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;

  for (const group of groupSubmittedBodyFields(schema, submission)) {
    y = drawSectionHeading(doc, group.title, y);

    const rows = group.fields.map(
      (field) =>
        [field.label, formatSubmissionDisplayValue(field, submission[field.key])] as [
          string,
          string,
        ],
    );

    y = drawLabelValueTable(doc, rows, y);
  }

  for (const field of getSubmittedFieldsInOrder(schema, submission)) {
    if (field.type !== 'repeater') {
      continue;
    }

    for (const section of buildRepeaterPdfSections(field, submission[field.key])) {
      y = drawSectionHeading(doc, section.title, y);
      y = drawLabelValueTable(doc, section.rows, y);
    }
  }

  const totalPages = doc.getNumberOfPages();

  for (let page = 1; page <= totalPages; page++) {
    doc.setPage(page);
    drawPageFooter(doc, page, totalPages);
  }

  const filename = `${sanitizeFilename(schema.id)}-submission.pdf`;
  doc.save(filename);
}
