export {
  SHELL_NAV_DESTINATIONS,
  navigateShellTo,
  clickBrandAndReturnHome,
  deepLinkProtectedAsGuest,
  deepLinkFormAsAuthenticated,
  logoutToLogin,
  browserBack,
  browserForward,
  type NavigateShellResult,
  type BrandHomeResult,
  type DeepLinkGuestResult,
  type DeepLinkFormResult,
  type LogoutNavResult,
  type HistoryNavResult,
} from './navigation.workflow';
